### ISSUE TITLE
Episode number being left out from save name

### ISSUE THREAD

**Issue by A-nglea** [Diazole/my5-dl#3]
the save name string misses the episode number and conflates with the episode tile
for example.
All.Creatures.Great.and.Small.S02ESemper.Progrediens.mp4   

Looking at your code I see this is by design. But for an episodes in a series which has a title and an episode number, if users download a whole series they will have no idea which to view first.   Clearly needs an episode number capturing and inserting.

And N_m3u8DL-RE handles DASH. And of course muxes all in one command.

**Comment by Diazole** [comment]
The latest commit should have fixed that
